# Generated by Django 3.2.4 on 2021-06-18 04:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='video_views',
            field=models.ManyToManyField(null=True, related_name='video_views', to=settings.AUTH_USER_MODEL),
        ),
    ]
